name: DocFX Documentation (Self-Hosted)
on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: cmd  # 모든 명령을 CMD로 실행

jobs:
  build:
    runs-on: self-hosted  # GitHub hosted runner 대신 self-hosted 사용
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Set PowerShell Execution Policy
      run: powershell.exe -ExecutionPolicy Bypass -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force"
      
    - name: Setup DocFX
      run: dotnet tool install -g docfx --version 2.61.0
      
    - name: Build Documentation
      run: |
        cd Documentation
        docfx docfx.json
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './Documentation/_site'
      shell: bash  # Git Bash 사용
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted  # GitHub hosted runner 대신 self-hosted 사용
    needs: build
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4